### PR TITLE
Added a simple structure for reading input configuration.

### PR DESCRIPTION
**Pull request by ogoding**
I did not feature gate it, as it would cause the engine to stop compiling, and the main thing we want to feature gate is the processing part anyway.

### CODE REVIEW

**Comment by ogoding** [comment]
I just remembered that I had forgotten to allow for modifiers (ctrl/alt/shift). (Here is an example of how I think I can do it)[https://gist.github.com/3f9474f82c667348fe7a8a784ccc33a2]. Any preference as to which one? Or do you have any ideas on other ways to do it?

**Comment by ebkalderon** [comment]
Thanks for the pull request, it looks pretty good! In response to your question, I'm not completely sure about how to handle modifiers. Do you think that using straight boolean fields indicating whether the modifier is held would do well as opposed to `Option`?

**Comment by ogoding** [comment]
Like this? https://gist.github.com/162245dd8734aaf687f134e928764400 I should be fine assuming that there is no need to distinguish between left and right modifiers, but I can't really think of a scenario in which anyone would want to do that for input :smile:

**Comment by ebkalderon** [comment]
That looks great. Yeah, I can't think of any scenarios for left and right modifiers either. :grin:

**Pull request closed without merging**
